name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
#    env:
#      POSTGRES_URL: ${{ vars.POSTGRES_URL }}
#      BLOB_READ_WRITE_TOKEN: ${{ vars.BLOB_READ_WRITE_TOKEN }}
#      PAYLOAD_SECRET: ${{ vars.PAYLOAD_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install dependencies
        run: npm install

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ matrix.environment }} --token=${{ secrets.VERCEL_TOKEN }}

#      - name: Migrate database
#        run: npm run migrate

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
