name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Echo environment
        run: echo "💡 Deploying to ${{ matrix.environment }}."

      - name: Install dependencies
        run: npm install

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Copy vercel .vercel/.env.preview.local to .env
        run: cp .vercel/.env.preview.local .env

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      - name: Migrate database
        run: npm run migrate
